apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: advanced
  namespace: 74cudwfj-expose-advanced-dev
  annotations:
    # Adds custom NGINX configuration to the Ingress.
    # This snippet disables the `X-Frame-Options` header, allowing the application to be embedded in iframes.
    nginx.ingress.kubernetes.io/configuration-snippet: 'more_set_headers X-Frame-Options: none;'
spec:
  rules:
    - host: backend-expose-advanced-74cudwfj-expose-advanced-dev.development.krci-dev.cloudmentor.academy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: root-service
                port:
                  number: 80
          - path: /api/hello
            pathType: Prefix
            backend:
              service:
                name: hello-service
                port:
                  number: 80
